apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: xnemect-surgeon-webapi-mongodb-init
    files:
      - params/init-db.js
  - name: xnemect-surgeon-webapi-config
    literals:
      - database=xnemect-surgeon
      - collection=surgeon
patches:
  - path: patches/webapi.deployment.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: xnemect-surgeon-webapi
