/*
 * Waiting List Api
 *
 * Surgeons List for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: tomas.nemec1999@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

 package surgeon_wl

import (
   "net/http"

   "github.com/gin-gonic/gin"
)

type OperatedLimbAPI interface {

   // internal registration of api routes
   addRoutes(routerGroup *gin.RouterGroup)

    // GetOperatedLimbList - Provides the list of operated limbs associated with surgeries
   GetOperatedLimbList(ctx *gin.Context)

 }

// partial implementation of OperatedLimbAPI - all functions must be implemented in add on files
type implOperatedLimbAPI struct {

}

func newOperatedLimbAPI() OperatedLimbAPI {
  return &implOperatedLimbAPI{}
}

func (this *implOperatedLimbAPI) addRoutes(routerGroup *gin.RouterGroup) {
  routerGroup.Handle( http.MethodGet, "/surgeries-list/operatedLimbList", this.GetOperatedLimbList)
}

// Copy following section to separate file, uncomment, and implement accordingly
// // GetOperatedLimbList - Provides the list of operated limbs associated with surgeries
// func (this *implOperatedLimbAPI) GetOperatedLimbList(ctx *gin.Context) {
//  	ctx.AbortWithStatus(http.StatusNotImplemented)
// }
//

