/*
 * Waiting List Api
 *
 * Surgeons List for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: tomas.nemec1999@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package surgeon_wl

type SurgeryEntry struct {

	// Unique id of the entry in this surgeries list
	Id string `json:"id"`

	// Unique identifier of the surgeon known to Web-In-Cloud system
	SurgeonId string `json:"surgeonId"`

	// Unique identifier of the patient known to Web-In-Cloud system
	PatientId string `json:"patientId"`

	Date string `json:"date"`

	Successful bool `json:"successful"`

	SurgeryNote string `json:"surgeryNote,omitempty"`

	OperatedLimb OperatedLimb `json:"operatedLimb"`
}
