/*
 * Waiting List Api
 *
 * Surgeons List for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: tomas.nemec1999@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package surgeon_wl

// OperatedLimb - Location on body that was operated
type OperatedLimb struct {

	Value string `json:"value"`

	Code string `json:"code,omitempty"`
}
