/*
 * Waiting List Api
 *
 * Surgeons List for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: tomas.nemec1999@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package surgeon_wl

import (
    "github.com/gin-gonic/gin"
)

func AddRoutes(engine *gin.Engine) {
  group := engine.Group("/api")
  
  {
    api := newOperatedLimbAPI()
    api.addRoutes(group)
  }
  
  {
    api := newSurgeonsAPI()
    api.addRoutes(group)
  }
  
  {
    api := newSurgeriesAPI()
    api.addRoutes(group)
  }
  
}